name: "ECLAIR"
on: [push]
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ANALYSIS_KIND: normal
  ENABLE_ECLAIR_BOT: true
jobs:
  Analyze:
    runs-on: eclairit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build and analyze with ECLAIR
        run: |
          set -eu
          ./prepare.sh Debug
          ./ECLAIR/analyze.sh "${ANALYSIS_KIND}"
      - name: ECLAIR analysis log
        if: always()
        run: cat ECLAIR_out/ANALYSIS.log
      - name: ECLAIR report log
        if: always()
        run: cat ECLAIR_out/REPORT.log
      - name: Upload ECLAIR artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ECLAIR_out*/
      - name: Upload ECLAIR SARIF
        uses: BUGSENG/codeql-action/upload-sarif@v2
        with:
          sarif_file: ECLAIR_out/reports.sarif
          category: "eclair-normal"
      - name: Publish ECLAIR results
        env:
          WTOKEN: ${{secrets.WTOKEN}}
        run: ECLAIR/action_push.sh "${WTOKEN}" ECLAIR_out
